### ISSUE TITLE
Handwheel operation causes lockup

### ISSUE THREAD

**Issue by ryansturmer** [ShopBotTools/FabMo-Engine#78]
Handwheel operation sometimes causes the tool to "stick" in the manual mode.  In certain circumstances, G2 seems to stop accepting the queue flush, making it impossible to exit the manual mode.  

To reproduce:  Just drive the handwheel around some.  It seems to happen more often with short moves.

**Comment by ryansturmer** [comment]
This seems to be mostly OK in the current version.

**Comment by aldenhart** [comment]
Good. Please let us know if you experience any other issues with this.

Alden
